---
title: "Data Visualization"
author: "Aniket Singh"
date: "2/1/2021"
output:
  md_document:
    variant: gfm
  html_document:
    df_print: paged
---

```{r Loading the packages}
library(tidyverse)
library(dplyr)
library(VIM)
library(readr)
```
```{r Reading the data}
airbnb <- read_csv("/Users/aniketsingh/AirBnbSeniorProject/data/AB_NYC_2019.csv")
```


```{r Selecting the variables}
# Imputing the missing values of the column reviews_per_month to 0.
airbnb$reviews_per_month[is.na(airbnb$reviews_per_month)] <- 0

newdata <- select(airbnb, -id, -name, -host_id, -host_name)
str(newdata)

numericData <- select(newdata,price,latitude,longitude,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365)

charData <- select(newdata,price, neighbourhood_group, neighbourhood, room_type)

timeData <- select(newdata, price, last_review)
```

Univariate Graphs of Character Variables

```{r Distribution of Neighbourhood Group}
ggplot(charData, aes(x = neighbourhood_group,y = ..count.. / sum(..count..))) + 
  geom_bar(fill = "yellow",
color="black") +
  labs(x = "Neighbourhood Group",
       y = "Frequency") +
  scale_y_continuous(labels = scales::percent)

```


```{r Distribution of Room Type}
ggplot(charData, aes(x = room_type,y = ..count.. / sum(..count..))) + 
  geom_bar(fill = "red",
color="black") +
  labs(x = "Room type",
       y = "Frequency") +
  scale_y_continuous(labels = scales::percent)
```

Univariate Graphs of Numeric Variables
```{r Distribution of price}
ggplot(filter(numericData,price < 1050), aes(x = price,y= ..count.. / sum(..count..))) + geom_histogram(fill = "cornflowerblue",
color = "white",bindwidth = 50) +
labs(title = "Price Distribution",
x = "Price") + scale_y_continuous(labels = scales::percent)
```

```{r Distribution of Minimum nights}
ggplot(filter(numericData,minimum_nights < 35), aes(x = minimum_nights,y= ..count.. / sum(..count..))) + geom_histogram(fill = "cornflowerblue",
color = "white", bindwidth = 1) +
labs(title = "Minimum Nights Distribution",
x = "Minimum nights") + scale_y_continuous(labels = scales::percent)
```

```{r Distribution of number_of_reviews}
ggplot(filter(numericData,number_of_reviews < 250), aes(x = number_of_reviews,y= ..count.. / sum(..count..))) + geom_histogram(fill = "cornflowerblue",
color = "white", bindwidth = 1) +
labs(title = "Distribution of number_of_reviews",
x = "Number Of Reviews") + scale_y_continuous(labels = scales::percent)
```

```{r Distribution of reviews_per_month}
ggplot(filter(numericData,reviews_per_month < 11), aes(x = reviews_per_month,y= ..count.. / sum(..count..))) + geom_histogram(fill = "cornflowerblue",
color = "white", bindwidth = 1) +
labs(title = "Distribution of reviews_per_month",
x = "Reviews per month") + scale_y_continuous(labels = scales::percent)
```
```{r Distribution of calculated_host_listings_count}
ggplot(filter(numericData,calculated_host_listings_count < 40), aes(x = calculated_host_listings_count,y= ..count.. / sum(..count..))) + geom_histogram(fill = "cornflowerblue",
color = "white", bins= 30) +
labs(title = "Distribution of calculated_host_listings_count",
x = "Calculated Host Listings Count") + scale_y_continuous(labels = scales::percent)
```
```{r Distribution of availability_365}
ggplot(numericData, aes(x = availability_365,y= ..count.. / sum(..count..))) + geom_histogram(fill = "cornflowerblue",
color = "white", bins= 30) +
labs(title = "Distribution of availability_365",
x = "Number of available days in a year") + scale_y_continuous(labels = scales::percent)
```

Bivariate Graphs
```{r Segmented Bar Chart of neighbourhood_group with neighbourhood}
ggplot(charData,
aes(x = neighbourhood_group,
fill = neighbourhood)) + geom_bar(position = "fill") +
labs(y = "Proportion")
```
```{r Segmented Bar Chart of Neighbourhood Group with Room Type}
ggplot(charData,
aes(x = neighbourhood_group,
fill = room_type)) + geom_bar(position = "fill") +
labs(y = "Proportion")
```
Kernel Density plot for quantitative vs categorical variables
```{r}
ggplot(filter(charData,price < 750),
aes(x = price, fill = neighbourhood_group)) +
geom_density(alpha = 0.4) +
labs(title = "Price distribution by neighbourhood group")
```
Distribution using violin and box plots.
```{r}
ggplot(charData, aes(x = neighbourhood_group,
y = price)) + geom_violin(fill = "cornflowerblue") + geom_boxplot(width = .01,
fill = "orange", outlier.color = "orange", outlier.size = 2) +
labs(title = "Price distribution by neighbourhood group")
```
